from distutils.core import setup
setup(
  name='dbf_read_iffy',
  py_modules=['dbf_read_iffy'],
  version='1.0',
  description="Read from dbf's if codepage is unsupported by modules dbf and codecs (895 cz Kamenicky, ..).",
  install_requires=['dbf'],
  author='Mirek Zvolsky',
  author_email='zvolsky@seznam.cz',
  url='https://github.com/zvolsky/dbf_read_iffy',
  download_url='https://github.com/zvolsky/dbf_read_iffy/tarball/1.0',
  keywords=['dbf', 'dbase', 'foxpro', 'vfp', '895', 'Kamenicky', '620', 'Mazovia', 'encoding'],
  classifiers=[
      'Development Status :: 5 - Production/Stable',
      'Intended Audience :: Developers',
      'Intended Audience :: Information Technology',
      'License :: OSI Approved :: MIT License',
      'Operating System :: OS Independent',
      'Topic :: Database',
      'Topic :: Database :: Database Engines/Servers',
      'Topic :: Software Development',
      'Programming Language :: Python',
      'Programming Language :: Python :: 2',
      'Programming Language :: Python :: 3',
      'Programming Language :: dBase',
      'Programming Language :: Foxpro',
      'Programming Language :: VFP',
  ],
)
